CREATE TABLE pet (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(60) NOT NULL,
    especie         VARCHAR(10) NOT NULL,
    raca            VARCHAR(60) NOT NULL,
    data_nascimento DATE        NOT NULL,
    tutor_id        BIGINT      NOT NULL,
    CONSTRAINT ck_pet_especie CHECK (especie IN ('CAO', 'GATO')),
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES usuario (id)
);
