CREATE TABLE agendamento (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id     BIGINT      NOT NULL,
    tipo       VARCHAR(20) NOT NULL,
    data       DATE        NOT NULL,
    status     VARCHAR(20) NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT ck_agendamento_tipo CHECK (tipo IN ('VACINA', 'VERMIFUGO', 'CHECKUP')),
    CONSTRAINT ck_agendamento_status CHECK (status IN ('SOLICITADO', 'CONFIRMADO', 'RECUSADO', 'REALIZADO')),
    CONSTRAINT fk_agendamento_pet FOREIGN KEY (pet_id) REFERENCES pet (id) ON DELETE CASCADE
);
